### ISSUE TITLE
Absolute path or reference to a PATH variable?

### ISSUE THREAD

**Issue by gustaflindqvist** [grapefrukt/unity-builddata#1]
Love this script for builddata. Could it be a idea to reference PATH variable on Window 10 and Mac/Linux? 

Windows 10: `System.Environment.GetEnvironmentVariable("GIT_HOME", EnvironmentVariableTarget.Machine);`

It might work on Mac and Linux as well: https://docs.microsoft.com/en-us/dotnet/api/system.environment.getenvironmentvariable

https://github.com/grapefrukt/unity-builddata/blob/bf643dc20fcd949c7e0c9d02d8bc84bd4770dbac/Editor/BuildDataEditor.cs#L19

**Comment by grapefrukt** [comment]
I can't seem to find GIT_HOME set on either my Windows 10 or OS X machines, but it's definitely possible to be smarter about finding the executable! I'll leave that as an exercise for the reader.
